/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#9f3c16",
        "on-primary": "#ffffff",
        "primary-container": "#bf542c",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59c",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#822801",
        "inverse-primary": "#ffb59c",

        secondary: "#2c694e",
        "on-secondary": "#ffffff",
        "secondary-container": "#aeeecb",
        "on-secondary-container": "#316e52",
        "secondary-fixed": "#b1f0ce",
        "secondary-fixed-dim": "#95d4b3",
        "on-secondary-fixed": "#002114",
        "on-secondary-fixed-variant": "#0e5138",

        tertiary: "#815215",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#9d6a2c",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcbb",
        "tertiary-fixed-dim": "#faba75",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#673d00",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        background: "#fff8f6",
        "on-background": "#221a18",
        surface: "#fff8f6",
        "on-surface": "#221a18",
        "surface-variant": "#efdfdb",
        "on-surface-variant": "#57423b",
        "surface-dim": "#e6d7d3",
        "surface-bright": "#fff8f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ed",
        "surface-container": "#fbeae7",
        "surface-container-high": "#f5e5e1",
        "surface-container-highest": "#efdfdb",

        outline: "#8a726a",
        "outline-variant": "#dec0b7",
        "inverse-surface": "#372e2c",
        "inverse-on-surface": "#fdedea",
        "surface-tint": "#a23e18",
      },
      borderRadius: { 
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        full: "9999px" 
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2.5rem",
        gutter: "1rem",
        "gutter-tablet": "1.25rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "currency-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", fontWeight: "600" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "title-lg": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "600" }],
        "currency-md": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
